name: Release

permissions:
  contents: write

on:
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    name: Build and Publish ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            os: windows-latest
            node: 22.18.0
          - name: MacOS
            os: macOS-latest
            node: 22.18.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      # 新增步骤：修改 @vitejs/plugin-vue 的 package.json
      - name: Add "types" field to @vitejs/plugin-vue/package.json (macOS)
        if: matrix.os == 'macOS-latest' # 仅在 macOS 执行
        run: |
          jq '.types = "./dist/index.d.ts"' node_modules/@vitejs/plugin-vue/package.json > temp.json && \
          mv temp.json node_modules/@vitejs/plugin-vue/package.json
        shell: bash

      - name: Add "types" field to @vitejs/plugin-vue/package.json (Windows)
        if: matrix.os == 'windows-latest' # 仅在 Windows 执行
        run: |
          jq '.types = "./dist/index.d.ts"' node_modules/@vitejs/plugin-vue/package.json | Out-File -Encoding utf8 temp.json
          Move-Item -Path temp.json -Destination node_modules/@vitejs/plugin-vue/package.json -Force
        shell: pwsh

      - name: Build for Windows
        if: contains(matrix.os, 'windows')
        run: npm run build:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build for MacOS
        if: contains(matrix.os, 'macOS')
        run: npm run build:mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
