name: Release

permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  build:
    name: Build and Publish ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
            - name: Windows
              os: windows-latest
              node: 22.18.0
            - name: MacOS
              os: macOS-latest
              node: 22.18.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Build for Windows
        if: contains(matrix.os, 'windows')
        run: npm run build:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build for MacOS
        if: contains(matrix.os, 'macOS')
        run: npm run build:mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
